### ISSUE TITLE
How to compile Marlin for STM32F103C8?

### ISSUE THREAD

**Issue by trieudung77** [Alfrederson/cncstm32#2]

**Comment by trieudung77** [comment]
> I have made a circuit board using STM32F103C8T6 to control a 3D printer, but when I upload the Marlin firmware to the STM32, I get the following error:
> 
> ```
> [upload] AssertionError :
> Traceback (most recent call last):
> File "C:\Users\Dung\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Action.py", line 1441, in execute
> result = self.execfunction(target=target, source=rsources, env=env)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\Dung\.platformio\platforms\atmelavr\builder\main.py", line 54, in BeforeUpload
> env.AutodetectUploadPort()
> File "C:\Users\Dung\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Util\envs.py", line 252, in __call__
> return self.method(*nargs, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\Dung\.platformio\penv\Lib\site-packages\platformio\builder\tools\pioupload.py", line 118, in AutodetectUploadPort
> ).find(initial_port)
> ^^^^^^^^^^^^^^^^^^
> File "C:\Users\Dung\.platformio\penv\Lib\site-packages\platformio\device\finder.py", line 147, in find
> device = self._find_known_device()
> ^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\Dung\.platformio\penv\Lib\site-packages\platformio\device\finder.py", line 245, in _find_known_device
> return wrapper()
> ^^^^^^^^^
> File "C:\Users\Dung\.platformio\penv\Lib\site-packages\platformio\util.py", line 113, in wrapper
> return func(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\Dung\.platformio\penv\Lib\site-packages\platformio\device\finder.py", line 240, in wrapper
> device = self.match_device_hwid(_fetch_hwids_from_platforms())
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\Dung\.platformio\penv\Lib\site-packages\platformio\device\finder.py", line 227, in _fetch_hwids_from_platforms
> for board_config in p.get_boards().values():
> ^^^^^^^^^^^^^^
> File "C:\Users\Dung\.platformio\platforms\atmelsam\platform.py", line 102, in get_boards
> result[key] = self._add_default_debug_tools(result[key])
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\Dung\.platformio\platforms\atmelsam\platform.py", line 151, in _add_default_debug_tools
> assert openocd_chipname
> AssertionError
> ```
> 
> I found a similar post titled: 'How to compile this for STM32F103C8/CB?'. Have you resolved it yet? Can you help me?
